#pragma once

#define TINY_ENGINE_BUILD_DEBUG			(!NDEBUG)
#define TINY_ENGINE_BUILD_RELEASE		(!TINY_ENGINE_BUILD_DEBUG)

#define TINY_ENGINE_PLATFOM_WINDOWS		(defined(_WIN32))
#define TINY_ENGINE_PLATFOM_LINUX		(defined(__unix))

#define TINY_ENGINE_COMPILER_CLANG		(__clang__ > 0L)
#define TINY_ENGINE_COMPILER_MSVC		((_MSC_VER > 0L) && !(TINY_ENGINE_COMPILER_CLANG))
#define TINY_ENGINE_COMPILER_GCC		((__GNUC__ > 0L) && !(TINY_ENGINE_COMPILER_CLANG))
